import { Project } from "../ListProject";
const fakeData = [
  {
    Id: "1",
    UserId: "U001",
    Title: "Dự án Xây dựng",
    Logo: "https://marketplace.canva.com/EAFKTnSY2XI/1/0/1600w/canva-red-white-simple-volunteer-community-logo-259ogEWC6Wo.jpg",
    Description: "Dự án xây dựng khu đô thị mới.",
    StartDate: "25-2-2025",
    EndDate: "1-3-2025",
    Address: "123 Đường ABC, TP. HCM",
    Campaign: "Spring",
    limitedNumber: 10,
    Status: "Đang thực hiện",
  },
  {
    Id: "2",
    UserId: "U002",
    Title: "Ứng dụng Quản lý",
    Logo: "https://media.istockphoto.com/id/931069122/vector/icon-with-the-concept-of-family-care-care-about-humanity.jpg?s=612x612&w=0&k=20&c=RWgHjgTaVOwdSQtPQcqQcTZ8t0MHdie7Jr0bnHZKvZc=",
    Description: "Ứng dụng quản lý công việc nhóm.",
    StartDate: "22-2-2025",
    EndDate: "5-3-2025",
    Address: "456 Đường XYZ, Hà Nội",
    Campaign: "Warm Winter",
    limitedNumber: 20,
    Status: "Hoàn thành",
  },
  {
    Id: "3",
    UserId: "U003",
    Title: "Dự án Nông nghiệp",
    Logo: "https://images-platform.99static.com//D2CeTd7AtniZOsk7xh-7hUoH5uA=/369x369:1650x1650/fit-in/500x500/99designs-contests-attachments/102/102378/attachment_102378453",
    Description: "Mô hình trồng trọt thông minh.",
    StartDate: "27-2-2025",
    EndDate: "7-3-2025",
    Address: "789 Đường LMN, Đà Nẵng",
    Campaign: "Warm Winter ",
    limitedNumber: 15,
    Status: "Đang thực hiện",
  },
  {
    Id: "4",
    UserId: "U004",
    Title: "Rửa cống sông Hồng",
    Logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx1Jd3es7AQv1pbnn4_jhhQaJr-OPdeEqdiw&s",
    Description: "Yêu cầu độ tuổi từ 18-30, có thể tham gia trực tiếp, yêu cầu từng có kinh nghiệm tham gia các dự án tương tự",
    StartDate: "21-2-2025",
    EndDate: "3-3-2025",
    Address: "12 Đường Láng, Hà Nội",
    Campaign: "Green Summer",
    limitedNumber: 20,
    Status: "Hoạt động",
  },
  {
    Id: "5",
    UserId: "U005",
    Title: "Nhặt rác xunh quanh sông Tô Lịch",
    Logo: "https://images-platform.99static.com//D2CeTd7AtniZOsk7xh-7hUoH5uA=/369x369:1650x1650/fit-in/500x500/99designs-contests-attachments/102/102378/attachment_102378453",
    Description: "Quyên góp ủng hộ, có chứng nhận tham gia hoạt động, yêu cầu từng có kinh nghiệm tham gia các dự án tương tự",
    StartDate: "24-2-2025",
    EndDate: "3-3-2025",
    Address: "12 Đường Láng, Hà Nội",
    limitedNumber: 25,
    Status: "Hoạt động",
  },
];

const tableHeaders = [
  { label: "ID", value: "Id" },
  { label: "User ID", value: "UserId" },
  { label: "Tiêu đề", value: "Title" },
  { label: "Mô tả", value: "Description" },
  { label: "Địa chỉ", value: "Address" },
  { label: "Số lượng giới hạn", value: "limitedNumber" },
  { label: "Trạng thái", value: "Status" },
];

export { fakeData, tableHeaders };
